//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace CenIT.Solution.Reports.SCT {
    
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("Data_TinhHinhHoatDong_SXKD")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class Data_TinhHinhHoatDong_SXKD : global::System.Data.DataSet {
        
        private TinhHinhHoatDong_SXKDDataTable tableTinhHinhHoatDong_SXKD;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public Data_TinhHinhHoatDong_SXKD() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected Data_TinhHinhHoatDong_SXKD(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["TinhHinhHoatDong_SXKD"] != null)) {
                    base.Tables.Add(new TinhHinhHoatDong_SXKDDataTable(ds.Tables["TinhHinhHoatDong_SXKD"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public TinhHinhHoatDong_SXKDDataTable TinhHinhHoatDong_SXKD {
            get {
                return this.tableTinhHinhHoatDong_SXKD;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public override global::System.Data.DataSet Clone() {
            Data_TinhHinhHoatDong_SXKD cln = ((Data_TinhHinhHoatDong_SXKD)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["TinhHinhHoatDong_SXKD"] != null)) {
                    base.Tables.Add(new TinhHinhHoatDong_SXKDDataTable(ds.Tables["TinhHinhHoatDong_SXKD"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        internal void InitVars(bool initTable) {
            this.tableTinhHinhHoatDong_SXKD = ((TinhHinhHoatDong_SXKDDataTable)(base.Tables["TinhHinhHoatDong_SXKD"]));
            if ((initTable == true)) {
                if ((this.tableTinhHinhHoatDong_SXKD != null)) {
                    this.tableTinhHinhHoatDong_SXKD.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private void InitClass() {
            this.DataSetName = "Data_TinhHinhHoatDong_SXKD";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/Data_TinhHinhHoatDong_SXKD.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tableTinhHinhHoatDong_SXKD = new TinhHinhHoatDong_SXKDDataTable();
            base.Tables.Add(this.tableTinhHinhHoatDong_SXKD);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private bool ShouldSerializeTinhHinhHoatDong_SXKD() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            Data_TinhHinhHoatDong_SXKD ds = new Data_TinhHinhHoatDong_SXKD();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public delegate void TinhHinhHoatDong_SXKDRowChangeEventHandler(object sender, TinhHinhHoatDong_SXKDRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class TinhHinhHoatDong_SXKDDataTable : global::System.Data.TypedTableBase<TinhHinhHoatDong_SXKDRow> {
            
            private global::System.Data.DataColumn columnTT;
            
            private global::System.Data.DataColumn columnChiTieu;
            
            private global::System.Data.DataColumn columnDonViTinh;
            
            private global::System.Data.DataColumn columnKeHoachNam;
            
            private global::System.Data.DataColumn columnNamTruoc_ThucHienThangBC;
            
            private global::System.Data.DataColumn columnNamTruoc_CongDon;
            
            private global::System.Data.DataColumn columnNamBC_ThucHienThangTruoc;
            
            private global::System.Data.DataColumn columnNamBC_UocThucHienThangBC;
            
            private global::System.Data.DataColumn columnNamBC_CongDonDenThangBC;
            
            private global::System.Data.DataColumn columnCongDon_ThangBC_KeHoachNam;
            
            private global::System.Data.DataColumn columnCongDon_ThangBC_CungKy;
            
            private global::System.Data.DataColumn columnThucHien_ThangBC_CungKy;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public TinhHinhHoatDong_SXKDDataTable() {
                this.TableName = "TinhHinhHoatDong_SXKD";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal TinhHinhHoatDong_SXKDDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected TinhHinhHoatDong_SXKDDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn TTColumn {
                get {
                    return this.columnTT;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn ChiTieuColumn {
                get {
                    return this.columnChiTieu;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn DonViTinhColumn {
                get {
                    return this.columnDonViTinh;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn KeHoachNamColumn {
                get {
                    return this.columnKeHoachNam;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn NamTruoc_ThucHienThangBCColumn {
                get {
                    return this.columnNamTruoc_ThucHienThangBC;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn NamTruoc_CongDonColumn {
                get {
                    return this.columnNamTruoc_CongDon;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn NamBC_ThucHienThangTruocColumn {
                get {
                    return this.columnNamBC_ThucHienThangTruoc;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn NamBC_UocThucHienThangBCColumn {
                get {
                    return this.columnNamBC_UocThucHienThangBC;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn NamBC_CongDonDenThangBCColumn {
                get {
                    return this.columnNamBC_CongDonDenThangBC;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn CongDon_ThangBC_KeHoachNamColumn {
                get {
                    return this.columnCongDon_ThangBC_KeHoachNam;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn CongDon_ThangBC_CungKyColumn {
                get {
                    return this.columnCongDon_ThangBC_CungKy;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn ThucHien_ThangBC_CungKyColumn {
                get {
                    return this.columnThucHien_ThangBC_CungKy;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public TinhHinhHoatDong_SXKDRow this[int index] {
                get {
                    return ((TinhHinhHoatDong_SXKDRow)(this.Rows[index]));
                }
            }
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event TinhHinhHoatDong_SXKDRowChangeEventHandler TinhHinhHoatDong_SXKDRowChanging;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event TinhHinhHoatDong_SXKDRowChangeEventHandler TinhHinhHoatDong_SXKDRowChanged;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event TinhHinhHoatDong_SXKDRowChangeEventHandler TinhHinhHoatDong_SXKDRowDeleting;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event TinhHinhHoatDong_SXKDRowChangeEventHandler TinhHinhHoatDong_SXKDRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void AddTinhHinhHoatDong_SXKDRow(TinhHinhHoatDong_SXKDRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public TinhHinhHoatDong_SXKDRow AddTinhHinhHoatDong_SXKDRow(string TT, string ChiTieu, string DonViTinh, string KeHoachNam, string NamTruoc_ThucHienThangBC, string NamTruoc_CongDon, string NamBC_ThucHienThangTruoc, string NamBC_UocThucHienThangBC, string NamBC_CongDonDenThangBC, string CongDon_ThangBC_KeHoachNam, string CongDon_ThangBC_CungKy, string ThucHien_ThangBC_CungKy) {
                TinhHinhHoatDong_SXKDRow rowTinhHinhHoatDong_SXKDRow = ((TinhHinhHoatDong_SXKDRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        TT,
                        ChiTieu,
                        DonViTinh,
                        KeHoachNam,
                        NamTruoc_ThucHienThangBC,
                        NamTruoc_CongDon,
                        NamBC_ThucHienThangTruoc,
                        NamBC_UocThucHienThangBC,
                        NamBC_CongDonDenThangBC,
                        CongDon_ThangBC_KeHoachNam,
                        CongDon_ThangBC_CungKy,
                        ThucHien_ThangBC_CungKy};
                rowTinhHinhHoatDong_SXKDRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowTinhHinhHoatDong_SXKDRow);
                return rowTinhHinhHoatDong_SXKDRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public override global::System.Data.DataTable Clone() {
                TinhHinhHoatDong_SXKDDataTable cln = ((TinhHinhHoatDong_SXKDDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Data.DataTable CreateInstance() {
                return new TinhHinhHoatDong_SXKDDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal void InitVars() {
                this.columnTT = base.Columns["TT"];
                this.columnChiTieu = base.Columns["ChiTieu"];
                this.columnDonViTinh = base.Columns["DonViTinh"];
                this.columnKeHoachNam = base.Columns["KeHoachNam"];
                this.columnNamTruoc_ThucHienThangBC = base.Columns["NamTruoc_ThucHienThangBC"];
                this.columnNamTruoc_CongDon = base.Columns["NamTruoc_CongDon"];
                this.columnNamBC_ThucHienThangTruoc = base.Columns["NamBC_ThucHienThangTruoc"];
                this.columnNamBC_UocThucHienThangBC = base.Columns["NamBC_UocThucHienThangBC"];
                this.columnNamBC_CongDonDenThangBC = base.Columns["NamBC_CongDonDenThangBC"];
                this.columnCongDon_ThangBC_KeHoachNam = base.Columns["CongDon_ThangBC_KeHoachNam"];
                this.columnCongDon_ThangBC_CungKy = base.Columns["CongDon_ThangBC_CungKy"];
                this.columnThucHien_ThangBC_CungKy = base.Columns["ThucHien_ThangBC_CungKy"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            private void InitClass() {
                this.columnTT = new global::System.Data.DataColumn("TT", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnTT);
                this.columnChiTieu = new global::System.Data.DataColumn("ChiTieu", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnChiTieu);
                this.columnDonViTinh = new global::System.Data.DataColumn("DonViTinh", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDonViTinh);
                this.columnKeHoachNam = new global::System.Data.DataColumn("KeHoachNam", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnKeHoachNam);
                this.columnNamTruoc_ThucHienThangBC = new global::System.Data.DataColumn("NamTruoc_ThucHienThangBC", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnNamTruoc_ThucHienThangBC);
                this.columnNamTruoc_CongDon = new global::System.Data.DataColumn("NamTruoc_CongDon", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnNamTruoc_CongDon);
                this.columnNamBC_ThucHienThangTruoc = new global::System.Data.DataColumn("NamBC_ThucHienThangTruoc", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnNamBC_ThucHienThangTruoc);
                this.columnNamBC_UocThucHienThangBC = new global::System.Data.DataColumn("NamBC_UocThucHienThangBC", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnNamBC_UocThucHienThangBC);
                this.columnNamBC_CongDonDenThangBC = new global::System.Data.DataColumn("NamBC_CongDonDenThangBC", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnNamBC_CongDonDenThangBC);
                this.columnCongDon_ThangBC_KeHoachNam = new global::System.Data.DataColumn("CongDon_ThangBC_KeHoachNam", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCongDon_ThangBC_KeHoachNam);
                this.columnCongDon_ThangBC_CungKy = new global::System.Data.DataColumn("CongDon_ThangBC_CungKy", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCongDon_ThangBC_CungKy);
                this.columnThucHien_ThangBC_CungKy = new global::System.Data.DataColumn("ThucHien_ThangBC_CungKy", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnThucHien_ThangBC_CungKy);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public TinhHinhHoatDong_SXKDRow NewTinhHinhHoatDong_SXKDRow() {
                return ((TinhHinhHoatDong_SXKDRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new TinhHinhHoatDong_SXKDRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Type GetRowType() {
                return typeof(TinhHinhHoatDong_SXKDRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.TinhHinhHoatDong_SXKDRowChanged != null)) {
                    this.TinhHinhHoatDong_SXKDRowChanged(this, new TinhHinhHoatDong_SXKDRowChangeEvent(((TinhHinhHoatDong_SXKDRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.TinhHinhHoatDong_SXKDRowChanging != null)) {
                    this.TinhHinhHoatDong_SXKDRowChanging(this, new TinhHinhHoatDong_SXKDRowChangeEvent(((TinhHinhHoatDong_SXKDRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.TinhHinhHoatDong_SXKDRowDeleted != null)) {
                    this.TinhHinhHoatDong_SXKDRowDeleted(this, new TinhHinhHoatDong_SXKDRowChangeEvent(((TinhHinhHoatDong_SXKDRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.TinhHinhHoatDong_SXKDRowDeleting != null)) {
                    this.TinhHinhHoatDong_SXKDRowDeleting(this, new TinhHinhHoatDong_SXKDRowChangeEvent(((TinhHinhHoatDong_SXKDRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void RemoveTinhHinhHoatDong_SXKDRow(TinhHinhHoatDong_SXKDRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                Data_TinhHinhHoatDong_SXKD ds = new Data_TinhHinhHoatDong_SXKD();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "TinhHinhHoatDong_SXKDDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        public partial class TinhHinhHoatDong_SXKDRow : global::System.Data.DataRow {
            
            private TinhHinhHoatDong_SXKDDataTable tableTinhHinhHoatDong_SXKD;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal TinhHinhHoatDong_SXKDRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tableTinhHinhHoatDong_SXKD = ((TinhHinhHoatDong_SXKDDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string TT {
                get {
                    try {
                        return ((string)(this[this.tableTinhHinhHoatDong_SXKD.TTColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'TT\' in table \'TinhHinhHoatDong_SXKD\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableTinhHinhHoatDong_SXKD.TTColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string ChiTieu {
                get {
                    try {
                        return ((string)(this[this.tableTinhHinhHoatDong_SXKD.ChiTieuColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'ChiTieu\' in table \'TinhHinhHoatDong_SXKD\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableTinhHinhHoatDong_SXKD.ChiTieuColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string DonViTinh {
                get {
                    try {
                        return ((string)(this[this.tableTinhHinhHoatDong_SXKD.DonViTinhColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'DonViTinh\' in table \'TinhHinhHoatDong_SXKD\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableTinhHinhHoatDong_SXKD.DonViTinhColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string KeHoachNam {
                get {
                    try {
                        return ((string)(this[this.tableTinhHinhHoatDong_SXKD.KeHoachNamColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'KeHoachNam\' in table \'TinhHinhHoatDong_SXKD\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableTinhHinhHoatDong_SXKD.KeHoachNamColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string NamTruoc_ThucHienThangBC {
                get {
                    try {
                        return ((string)(this[this.tableTinhHinhHoatDong_SXKD.NamTruoc_ThucHienThangBCColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'NamTruoc_ThucHienThangBC\' in table \'TinhHinhHoatDong_SXKD\' " +
                                "is DBNull.", e);
                    }
                }
                set {
                    this[this.tableTinhHinhHoatDong_SXKD.NamTruoc_ThucHienThangBCColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string NamTruoc_CongDon {
                get {
                    try {
                        return ((string)(this[this.tableTinhHinhHoatDong_SXKD.NamTruoc_CongDonColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'NamTruoc_CongDon\' in table \'TinhHinhHoatDong_SXKD\' is DBNul" +
                                "l.", e);
                    }
                }
                set {
                    this[this.tableTinhHinhHoatDong_SXKD.NamTruoc_CongDonColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string NamBC_ThucHienThangTruoc {
                get {
                    try {
                        return ((string)(this[this.tableTinhHinhHoatDong_SXKD.NamBC_ThucHienThangTruocColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'NamBC_ThucHienThangTruoc\' in table \'TinhHinhHoatDong_SXKD\' " +
                                "is DBNull.", e);
                    }
                }
                set {
                    this[this.tableTinhHinhHoatDong_SXKD.NamBC_ThucHienThangTruocColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string NamBC_UocThucHienThangBC {
                get {
                    try {
                        return ((string)(this[this.tableTinhHinhHoatDong_SXKD.NamBC_UocThucHienThangBCColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'NamBC_UocThucHienThangBC\' in table \'TinhHinhHoatDong_SXKD\' " +
                                "is DBNull.", e);
                    }
                }
                set {
                    this[this.tableTinhHinhHoatDong_SXKD.NamBC_UocThucHienThangBCColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string NamBC_CongDonDenThangBC {
                get {
                    try {
                        return ((string)(this[this.tableTinhHinhHoatDong_SXKD.NamBC_CongDonDenThangBCColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'NamBC_CongDonDenThangBC\' in table \'TinhHinhHoatDong_SXKD\' i" +
                                "s DBNull.", e);
                    }
                }
                set {
                    this[this.tableTinhHinhHoatDong_SXKD.NamBC_CongDonDenThangBCColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string CongDon_ThangBC_KeHoachNam {
                get {
                    try {
                        return ((string)(this[this.tableTinhHinhHoatDong_SXKD.CongDon_ThangBC_KeHoachNamColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'CongDon_ThangBC_KeHoachNam\' in table \'TinhHinhHoatDong_SXKD" +
                                "\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableTinhHinhHoatDong_SXKD.CongDon_ThangBC_KeHoachNamColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string CongDon_ThangBC_CungKy {
                get {
                    try {
                        return ((string)(this[this.tableTinhHinhHoatDong_SXKD.CongDon_ThangBC_CungKyColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'CongDon_ThangBC_CungKy\' in table \'TinhHinhHoatDong_SXKD\' is" +
                                " DBNull.", e);
                    }
                }
                set {
                    this[this.tableTinhHinhHoatDong_SXKD.CongDon_ThangBC_CungKyColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string ThucHien_ThangBC_CungKy {
                get {
                    try {
                        return ((string)(this[this.tableTinhHinhHoatDong_SXKD.ThucHien_ThangBC_CungKyColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'ThucHien_ThangBC_CungKy\' in table \'TinhHinhHoatDong_SXKD\' i" +
                                "s DBNull.", e);
                    }
                }
                set {
                    this[this.tableTinhHinhHoatDong_SXKD.ThucHien_ThangBC_CungKyColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsTTNull() {
                return this.IsNull(this.tableTinhHinhHoatDong_SXKD.TTColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetTTNull() {
                this[this.tableTinhHinhHoatDong_SXKD.TTColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsChiTieuNull() {
                return this.IsNull(this.tableTinhHinhHoatDong_SXKD.ChiTieuColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetChiTieuNull() {
                this[this.tableTinhHinhHoatDong_SXKD.ChiTieuColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsDonViTinhNull() {
                return this.IsNull(this.tableTinhHinhHoatDong_SXKD.DonViTinhColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetDonViTinhNull() {
                this[this.tableTinhHinhHoatDong_SXKD.DonViTinhColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsKeHoachNamNull() {
                return this.IsNull(this.tableTinhHinhHoatDong_SXKD.KeHoachNamColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetKeHoachNamNull() {
                this[this.tableTinhHinhHoatDong_SXKD.KeHoachNamColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsNamTruoc_ThucHienThangBCNull() {
                return this.IsNull(this.tableTinhHinhHoatDong_SXKD.NamTruoc_ThucHienThangBCColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetNamTruoc_ThucHienThangBCNull() {
                this[this.tableTinhHinhHoatDong_SXKD.NamTruoc_ThucHienThangBCColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsNamTruoc_CongDonNull() {
                return this.IsNull(this.tableTinhHinhHoatDong_SXKD.NamTruoc_CongDonColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetNamTruoc_CongDonNull() {
                this[this.tableTinhHinhHoatDong_SXKD.NamTruoc_CongDonColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsNamBC_ThucHienThangTruocNull() {
                return this.IsNull(this.tableTinhHinhHoatDong_SXKD.NamBC_ThucHienThangTruocColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetNamBC_ThucHienThangTruocNull() {
                this[this.tableTinhHinhHoatDong_SXKD.NamBC_ThucHienThangTruocColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsNamBC_UocThucHienThangBCNull() {
                return this.IsNull(this.tableTinhHinhHoatDong_SXKD.NamBC_UocThucHienThangBCColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetNamBC_UocThucHienThangBCNull() {
                this[this.tableTinhHinhHoatDong_SXKD.NamBC_UocThucHienThangBCColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsNamBC_CongDonDenThangBCNull() {
                return this.IsNull(this.tableTinhHinhHoatDong_SXKD.NamBC_CongDonDenThangBCColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetNamBC_CongDonDenThangBCNull() {
                this[this.tableTinhHinhHoatDong_SXKD.NamBC_CongDonDenThangBCColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsCongDon_ThangBC_KeHoachNamNull() {
                return this.IsNull(this.tableTinhHinhHoatDong_SXKD.CongDon_ThangBC_KeHoachNamColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetCongDon_ThangBC_KeHoachNamNull() {
                this[this.tableTinhHinhHoatDong_SXKD.CongDon_ThangBC_KeHoachNamColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsCongDon_ThangBC_CungKyNull() {
                return this.IsNull(this.tableTinhHinhHoatDong_SXKD.CongDon_ThangBC_CungKyColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetCongDon_ThangBC_CungKyNull() {
                this[this.tableTinhHinhHoatDong_SXKD.CongDon_ThangBC_CungKyColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsThucHien_ThangBC_CungKyNull() {
                return this.IsNull(this.tableTinhHinhHoatDong_SXKD.ThucHien_ThangBC_CungKyColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetThucHien_ThangBC_CungKyNull() {
                this[this.tableTinhHinhHoatDong_SXKD.ThucHien_ThangBC_CungKyColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public class TinhHinhHoatDong_SXKDRowChangeEvent : global::System.EventArgs {
            
            private TinhHinhHoatDong_SXKDRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public TinhHinhHoatDong_SXKDRowChangeEvent(TinhHinhHoatDong_SXKDRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public TinhHinhHoatDong_SXKDRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591